### ISSUE TITLE
cannot find the unique ID

### ISSUE THREAD

**Issue by elorigoni** [techtimo/spotmap#4]
in the new version of the spot map website, i don't have the url like your in the faq.
where I can find the uniqe id?

**Comment by elorigoni** [comment]
in maps.findmespot.com -  Shared Views I have a link like this:
https://maps.findmespot.com/s/XKZ8
and redirect to this link:
https://maps.findmespot.com/Track?ishr=0fe97049-d32b-485d-91d3-ab5f0107448b#panel-history
no one is the feed id...

**Comment by techtimo** [comment]
Hi @elorigoni,

sorry for the late response. For some reason I haven't been notified, or I missed it. 
Anyway:
Spot has changed quite a few things as I have just seen. I will look into this and try to update the plugin accordingly.
If you have anything more to share or some suggestions, I'm happy to hear them!

Thanks!

**Comment by techtimo** [comment]
There might be some API changes with the the map version they have released. Currently I have no active Spot subscription so it hard to understand for me. 
I have contacted the SPOT support on this, as currently they have no documentation on their website regarding API access.
If you have some more details to share, I am happy to hear them!

**Comment by techtimo** [comment]
I haven't heard back of the support yet, but after checking the provided link https://maps.findmespot.com/s/XKZ8 It seems that the old API will not work any longer. 


After looking at the new shared page it looks like we only need the `XKZ8` from the url.
Here is an outline to get the past points:

1. GET the new shared page: https://maps.findmespot.com/s/XKZ8 to retrieve the `.AspNet.ApplicationCookie` from the response header
1. with the gathered Cookie GET https://maps.findmespot.com/Track to retrieve a second cookie: `__RequestVerificationToken`
1. POST an empty obj with both Cookies https://maps.findmespot.com/services/GPSService.asmx/GetGroupsAndAssets to retrieve the AssetId (possible more than one) under `d.Assets` 
1. POST with both cookies for each assetId
https://maps.findmespot.com/services/GPSService.asmx/GetAssetPositionsForDateRange
with the following body:
```json
{
    "assetIds": "601267",
    "format": "M/D/YYYY h:mm:ss A",
    "fromDate": "5/14/2020 23:58",
    "lang": "en-US",
    "sensitivity": null,
    "toDate": "",
    "zoomLevel": null,
}
```

Via websockets we might get the latest 'real-time' updates.

**Comment by techtimo** [comment]
Ciao @elorigoni,
If you log in to your spot account you will see a section called "XML Feed" - click on it:

![my account spot](https://user-images.githubusercontent.com/22075114/83605701-a7514080-a578-11ea-9476-c76628607521.png)

After clicking on "create XML Feed", you can select what data you want to share and may protect it with a password:

![image003](https://user-images.githubusercontent.com/22075114/83605994-2777a600-a579-11ea-9adf-1d2e39abc5b5.png)

After you click create you will see the Feed Id, which you need to put in the spotmap settings page.

![image001](https://user-images.githubusercontent.com/22075114/83605973-20e92e80-a579-11ea-9ed1-52312d54997c.jpg)


Let me know if face any difficulties.

**Comment by elorigoni** [comment]
Hi,
I have tried to use the xml feed…but no results. I see on the map: “No data found”.
This is my xml feed:
07bNOnYeUGdYIqFy0b8Bd3uiFVjqgnzTk

It’s public

Elia

**Comment by elorigoni** [comment]
I have found this test interesting: maybe you can improve your plugin:
I have used an iframe code to include my shared maps.findmespot.com <http://maps.findmespot.com/> public share.
Look this code:
<iframe src="https://maps.findmespot.com/s/DS5X" frameborder="0" marginwidth="0" marginheight="0" width="100%" height="760"></iframe>

Elia

**Comment by techtimo** [comment]
Ciao @elorigoni,
Grazie per la tua risposta 🙂
I think there was an issue with the displaying on one of the previous versions of the Spotmap.
If you download or pull the latest changes, it should work and look like this:
![image](https://user-images.githubusercontent.com/22075114/83860253-5760ae00-a71f-11ea-9696-cfaf811d0842.png)
After the download please activate and deactivate the plugin.
you need to put your feed id there gain and also name the feed. (the name must match the name in the shortcode `devices=elia`).
There are some changes made in the db. The best is to just remove the spotmap_points table.
In case you want to keep the data in the db. Please run the following sql:
```sql
ALTER TABLE `wordpress`.`{PREFIX}_spotmap_points` 
ADD COLUMN `device` VARCHAR(100) NULL AFTER `custom_message`;
UPDATE {PREFIX}_spotmap_points SET device = 'elia' where 1;
```
and add to all entries the device name you will choose in the settings page.
Please use the following shortcode `[spotmap devices=elia colors=blue]`

If you like the iframe solution, you can just add the iframe to your posts or pages. In this case there is no need for a plugin.
So you might ask, what is the plugin there for?
Back in in the days when I developed this there was no history option for the share pages. 
It provides a cleaner interface and will load on the page faster

In future I would like to add a a filter for date ranges to select points only from this time, so it can be easily added in a post for a tour with just this data.
also i would like to have the possibilty to underlay a gpx track, which can be nice to see a planned route.

**Comment by elorigoni** [comment]
SUPER!!
I have use the “iframe” solution because I was thinking that with your plugin I have only the last 7 days points. But…you have improved the db!! So, all the point will be stored in the db…correct?
Can you guide me step-by-step for create the db? I don’t understand where I have to write the commands…
Thanks!!

elia

**Comment by techtimo** [comment]
Hey @elorigoni
the plugin will save all points in the DB, but the API accessed with the XML feed only provides data from the last 7 days.
So if you configure it today, it will get all points starting from last saturday to as long as you have the plugin activated and the spot subscription running 😃 

The easiest option to upgrade is if you don't care about the current points that are in the database:

1. upgrade to the newest version that I pushed one hour ago to Wordpress.org (0.7.5)
1. deactivate and deinstall the plugin. (While deinstalling the DB will be removed that's not happening with the older version 0.3.0)
1. install the plugin again and follow the installation / usage instruction

If you need the old data in the DB you need access to it, run the script in phpmyadmin or similar. I can provide you with further details if you like to keep the data in the db.

**Comment by elorigoni** [comment]
Fantastic.
Before I have deactivated and reactivated the plugin and the database was not cleaned.now, disinstalxled and reinstalled is running successful!! Yes, without last point but is not a problem…I’m testing the website for a 6month trip for the next year, and your plugin now is great.
You can add a button for remove a feed? Because you cannot remove it after save…

Elia

**Comment by techtimo** [comment]
not be able to remove a feed in the settings pages is definitely on the roadmap with the release of version 1.0.
I'm not yet very happy in how the feed data is stored in the database. I might change this first before adding the delete button. The easiest currently is delete the plugin and install it again....
or you change it directly in the db with mysql snippet here:
```sql
UPDATE `wp_options` SET `option_value` = 'a:1:{s:10:\"findmespot\";i:1;}' WHERE (`option_name` = 'spotmap_options');
```
that sets it back to 1 feed in the settings page.

**Comment by elorigoni** [comment]
Ok!
Thanks!!

Elia

**Comment by techtimo** [comment]
now the input fields will disappear if you leave the id empty. I will push it to Wordpress.org in a few days.

If there are things that you feel like they are missing, just open a new issue

**Comment by elorigoni** [comment]
Super Timo!
I will use the plugin, and if I find new things to improve, I’ll open an issue.
Elia

**Comment by elorigoni** [comment]
Hi timo!!
I have started my trip...8 month in Sentiero Italia, the longest Trek in
the world...
And I have a problem with tour plugin.
The First day, all the things go ok. After, the plugin dont load the new
position! Why? There Is a max data for the db?
Elia

Il dom 7 giu 2020, 23:55 Elia Origoni <elia.origoni@gmail.com> ha scritto:
