### ISSUE TITLE
Three things

### ISSUE THREAD

**Issue by suntri-star** [techtimo/spotmap#5]
1.) How long does it take if a point appears at SPOT until it is imported?
2.) I have two spots. How can I display both?
3.) I have set up one of the SPOT and do not see any points yet?

**Comment by suntri-star** [comment]
I can see entries from the SPOT with coordinates in the DB. But are they not shown on the map on the website?

**Comment by techtimo** [comment]
Hi @suntri-star,
1. It will take up to 2.5 minutes to be imported.
2. that is currently not supported, but if share some details with me I am happy to make this happen. 
3. spontaneously I cannot think of a reason for this. If you use WP 5 you could check out the `block-enabled` branch of the plugin, i have changed some details there.

Thanks for testing my plugin, I'm happy to get some more feedback of you. 
and sorry for the laste response, for some reason i did not get any mails about that.

**Comment by techtimo** [comment]
@suntri-star 
Regarding point 1: it is possible to speed this up. As soon as the wp-cron will find a new sent position it can reschedule the time to search for new position. 
As I have no active spot subscription currently, it is difficult to implement and test. If you like you can send me a mail for some collaboration. 😃

**Comment by suntri-star** [comment]
Please contact my directly on "thomas at rigert dot com"

**Comment by techtimo** [comment]
@suntri-star 
You have unread mails 😉

**Comment by techtimo** [comment]
fixed all issues:
support for multiple issues, improved display of markers on map
